
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  PageSnapshot: 'PageSnapshot',
  User: 'User',
  Interaction: 'Interaction',
  SnapshotWeb: 'SnapshotWeb',
  InteractionEvent: 'InteractionEvent',
  Application: 'Application',
  Account: 'Account',
  Activity: 'Activity',
  Project: 'Project',
  IpMap: 'IpMap'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const PageSnapshotScalarFieldEnum = {
  id: 'id',
  pagePath: 'pagePath',
  siteId: 'siteId',
  content: 'content',
  version: 'version',
  recordedOn: 'recordedOn'
} as const

export type PageSnapshotScalarFieldEnum = (typeof PageSnapshotScalarFieldEnum)[keyof typeof PageSnapshotScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastSeen: 'lastSeen',
  pagePath: 'pagePath',
  isLive: 'isLive',
  lastInteraction: 'lastInteraction'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const InteractionScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  userId: 'userId',
  pageId: 'pageId',
  pagePath: 'pagePath',
  windowWidth: 'windowWidth',
  windowHeight: 'windowHeight',
  userAgent: 'userAgent',
  ip: 'ip',
  city: 'city',
  region: 'region',
  country: 'country',
  latitude: 'latitude',
  longitude: 'longitude'
} as const

export type InteractionScalarFieldEnum = (typeof InteractionScalarFieldEnum)[keyof typeof InteractionScalarFieldEnum]


export const SnapshotWebScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  pageUrl: 'pageUrl',
  data: 'data',
  details: 'details',
  createdOn: 'createdOn'
} as const

export type SnapshotWebScalarFieldEnum = (typeof SnapshotWebScalarFieldEnum)[keyof typeof SnapshotWebScalarFieldEnum]


export const InteractionEventScalarFieldEnum = {
  id: 'id',
  interactionId: 'interactionId',
  type: 'type',
  x: 'x',
  y: 'y',
  scrollX: 'scrollX',
  scrollY: 'scrollY',
  element: 'element',
  value: 'value',
  key: 'key',
  timestamp: 'timestamp'
} as const

export type InteractionEventScalarFieldEnum = (typeof InteractionEventScalarFieldEnum)[keyof typeof InteractionEventScalarFieldEnum]


export const ApplicationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sites: 'sites',
  details: 'details',
  status: 'status'
} as const

export type ApplicationScalarFieldEnum = (typeof ApplicationScalarFieldEnum)[keyof typeof ApplicationScalarFieldEnum]


export const AccountScalarFieldEnum = {
  id: 'id',
  connectionId: 'connectionId',
  type: 'type',
  displayName: 'displayName',
  displayImage: 'displayImage',
  createdOn: 'createdOn',
  status: 'status',
  moreDetails: 'moreDetails'
} as const

export type AccountScalarFieldEnum = (typeof AccountScalarFieldEnum)[keyof typeof AccountScalarFieldEnum]


export const ActivityScalarFieldEnum = {
  id: 'id',
  identifierId: 'identifierId',
  type: 'type',
  timeSpent: 'timeSpent',
  agent: 'agent',
  moreDetails: 'moreDetails',
  ip: 'ip',
  userAgent: 'userAgent',
  pageUrl: 'pageUrl',
  referral: 'referral',
  contextId: 'contextId',
  geoLocation: 'geoLocation',
  activityOn: 'activityOn',
  projectId: 'projectId'
} as const

export type ActivityScalarFieldEnum = (typeof ActivityScalarFieldEnum)[keyof typeof ActivityScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  path: 'path',
  type: 'type',
  moreDetails: 'moreDetails',
  token: 'token',
  verifierKey: 'verifierKey',
  ipAddress: 'ipAddress',
  createdOn: 'createdOn'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const IpMapScalarFieldEnum = {
  id: 'id',
  ipAddress: 'ipAddress',
  ipType: 'ipType',
  city: 'city',
  region: 'region',
  country: 'country',
  geoLocation: 'geoLocation',
  ipInfo: 'ipInfo',
  moreDetails: 'moreDetails',
  lastUpdated: 'lastUpdated'
} as const

export type IpMapScalarFieldEnum = (typeof IpMapScalarFieldEnum)[keyof typeof IpMapScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

