
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `InteractionEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InteractionEvent
 * 
 */
export type InteractionEventModel = runtime.Types.Result.DefaultSelection<Prisma.$InteractionEventPayload>

export type AggregateInteractionEvent = {
  _count: InteractionEventCountAggregateOutputType | null
  _avg: InteractionEventAvgAggregateOutputType | null
  _sum: InteractionEventSumAggregateOutputType | null
  _min: InteractionEventMinAggregateOutputType | null
  _max: InteractionEventMaxAggregateOutputType | null
}

export type InteractionEventAvgAggregateOutputType = {
  x: number | null
  y: number | null
  scrollX: number | null
  scrollY: number | null
  timestamp: number | null
}

export type InteractionEventSumAggregateOutputType = {
  x: number | null
  y: number | null
  scrollX: number | null
  scrollY: number | null
  timestamp: number | null
}

export type InteractionEventMinAggregateOutputType = {
  id: string | null
  interactionId: string | null
  type: $Enums.InteractionEventType | null
  x: number | null
  y: number | null
  scrollX: number | null
  scrollY: number | null
  element: string | null
  value: string | null
  key: string | null
  timestamp: number | null
}

export type InteractionEventMaxAggregateOutputType = {
  id: string | null
  interactionId: string | null
  type: $Enums.InteractionEventType | null
  x: number | null
  y: number | null
  scrollX: number | null
  scrollY: number | null
  element: string | null
  value: string | null
  key: string | null
  timestamp: number | null
}

export type InteractionEventCountAggregateOutputType = {
  id: number
  interactionId: number
  type: number
  x: number
  y: number
  scrollX: number
  scrollY: number
  element: number
  value: number
  key: number
  timestamp: number
  _all: number
}


export type InteractionEventAvgAggregateInputType = {
  x?: true
  y?: true
  scrollX?: true
  scrollY?: true
  timestamp?: true
}

export type InteractionEventSumAggregateInputType = {
  x?: true
  y?: true
  scrollX?: true
  scrollY?: true
  timestamp?: true
}

export type InteractionEventMinAggregateInputType = {
  id?: true
  interactionId?: true
  type?: true
  x?: true
  y?: true
  scrollX?: true
  scrollY?: true
  element?: true
  value?: true
  key?: true
  timestamp?: true
}

export type InteractionEventMaxAggregateInputType = {
  id?: true
  interactionId?: true
  type?: true
  x?: true
  y?: true
  scrollX?: true
  scrollY?: true
  element?: true
  value?: true
  key?: true
  timestamp?: true
}

export type InteractionEventCountAggregateInputType = {
  id?: true
  interactionId?: true
  type?: true
  x?: true
  y?: true
  scrollX?: true
  scrollY?: true
  element?: true
  value?: true
  key?: true
  timestamp?: true
  _all?: true
}

export type InteractionEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InteractionEvent to aggregate.
   */
  where?: Prisma.InteractionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InteractionEvents to fetch.
   */
  orderBy?: Prisma.InteractionEventOrderByWithRelationInput | Prisma.InteractionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InteractionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InteractionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InteractionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InteractionEvents
  **/
  _count?: true | InteractionEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: InteractionEventAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: InteractionEventSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InteractionEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InteractionEventMaxAggregateInputType
}

export type GetInteractionEventAggregateType<T extends InteractionEventAggregateArgs> = {
      [P in keyof T & keyof AggregateInteractionEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInteractionEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateInteractionEvent[P]>
}




export type InteractionEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InteractionEventWhereInput
  orderBy?: Prisma.InteractionEventOrderByWithAggregationInput | Prisma.InteractionEventOrderByWithAggregationInput[]
  by: Prisma.InteractionEventScalarFieldEnum[] | Prisma.InteractionEventScalarFieldEnum
  having?: Prisma.InteractionEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InteractionEventCountAggregateInputType | true
  _avg?: InteractionEventAvgAggregateInputType
  _sum?: InteractionEventSumAggregateInputType
  _min?: InteractionEventMinAggregateInputType
  _max?: InteractionEventMaxAggregateInputType
}

export type InteractionEventGroupByOutputType = {
  id: string
  interactionId: string
  type: $Enums.InteractionEventType
  x: number | null
  y: number | null
  scrollX: number | null
  scrollY: number | null
  element: string | null
  value: string | null
  key: string | null
  timestamp: number
  _count: InteractionEventCountAggregateOutputType | null
  _avg: InteractionEventAvgAggregateOutputType | null
  _sum: InteractionEventSumAggregateOutputType | null
  _min: InteractionEventMinAggregateOutputType | null
  _max: InteractionEventMaxAggregateOutputType | null
}

export type GetInteractionEventGroupByPayload<T extends InteractionEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InteractionEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InteractionEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InteractionEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InteractionEventGroupByOutputType[P]>
      }
    >
  >



export type InteractionEventWhereInput = {
  AND?: Prisma.InteractionEventWhereInput | Prisma.InteractionEventWhereInput[]
  OR?: Prisma.InteractionEventWhereInput[]
  NOT?: Prisma.InteractionEventWhereInput | Prisma.InteractionEventWhereInput[]
  id?: Prisma.StringFilter<"InteractionEvent"> | string
  interactionId?: Prisma.StringFilter<"InteractionEvent"> | string
  type?: Prisma.EnumInteractionEventTypeFilter<"InteractionEvent"> | $Enums.InteractionEventType
  x?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  y?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  scrollX?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  scrollY?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  element?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  value?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  key?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  timestamp?: Prisma.IntFilter<"InteractionEvent"> | number
  interaction?: Prisma.XOR<Prisma.InteractionScalarRelationFilter, Prisma.InteractionWhereInput>
}

export type InteractionEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  x?: Prisma.SortOrderInput | Prisma.SortOrder
  y?: Prisma.SortOrderInput | Prisma.SortOrder
  scrollX?: Prisma.SortOrderInput | Prisma.SortOrder
  scrollY?: Prisma.SortOrderInput | Prisma.SortOrder
  element?: Prisma.SortOrderInput | Prisma.SortOrder
  value?: Prisma.SortOrderInput | Prisma.SortOrder
  key?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  interaction?: Prisma.InteractionOrderByWithRelationInput
}

export type InteractionEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.InteractionEventWhereInput | Prisma.InteractionEventWhereInput[]
  OR?: Prisma.InteractionEventWhereInput[]
  NOT?: Prisma.InteractionEventWhereInput | Prisma.InteractionEventWhereInput[]
  interactionId?: Prisma.StringFilter<"InteractionEvent"> | string
  type?: Prisma.EnumInteractionEventTypeFilter<"InteractionEvent"> | $Enums.InteractionEventType
  x?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  y?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  scrollX?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  scrollY?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  element?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  value?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  key?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  timestamp?: Prisma.IntFilter<"InteractionEvent"> | number
  interaction?: Prisma.XOR<Prisma.InteractionScalarRelationFilter, Prisma.InteractionWhereInput>
}, "id">

export type InteractionEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  x?: Prisma.SortOrderInput | Prisma.SortOrder
  y?: Prisma.SortOrderInput | Prisma.SortOrder
  scrollX?: Prisma.SortOrderInput | Prisma.SortOrder
  scrollY?: Prisma.SortOrderInput | Prisma.SortOrder
  element?: Prisma.SortOrderInput | Prisma.SortOrder
  value?: Prisma.SortOrderInput | Prisma.SortOrder
  key?: Prisma.SortOrderInput | Prisma.SortOrder
  timestamp?: Prisma.SortOrder
  _count?: Prisma.InteractionEventCountOrderByAggregateInput
  _avg?: Prisma.InteractionEventAvgOrderByAggregateInput
  _max?: Prisma.InteractionEventMaxOrderByAggregateInput
  _min?: Prisma.InteractionEventMinOrderByAggregateInput
  _sum?: Prisma.InteractionEventSumOrderByAggregateInput
}

export type InteractionEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.InteractionEventScalarWhereWithAggregatesInput | Prisma.InteractionEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.InteractionEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InteractionEventScalarWhereWithAggregatesInput | Prisma.InteractionEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InteractionEvent"> | string
  interactionId?: Prisma.StringWithAggregatesFilter<"InteractionEvent"> | string
  type?: Prisma.EnumInteractionEventTypeWithAggregatesFilter<"InteractionEvent"> | $Enums.InteractionEventType
  x?: Prisma.IntNullableWithAggregatesFilter<"InteractionEvent"> | number | null
  y?: Prisma.IntNullableWithAggregatesFilter<"InteractionEvent"> | number | null
  scrollX?: Prisma.IntNullableWithAggregatesFilter<"InteractionEvent"> | number | null
  scrollY?: Prisma.IntNullableWithAggregatesFilter<"InteractionEvent"> | number | null
  element?: Prisma.StringNullableWithAggregatesFilter<"InteractionEvent"> | string | null
  value?: Prisma.StringNullableWithAggregatesFilter<"InteractionEvent"> | string | null
  key?: Prisma.StringNullableWithAggregatesFilter<"InteractionEvent"> | string | null
  timestamp?: Prisma.IntWithAggregatesFilter<"InteractionEvent"> | number
}

export type InteractionEventCreateInput = {
  id?: string
  type: $Enums.InteractionEventType
  x?: number | null
  y?: number | null
  scrollX?: number | null
  scrollY?: number | null
  element?: string | null
  value?: string | null
  key?: string | null
  timestamp: number
  interaction: Prisma.InteractionCreateNestedOneWithoutEventsInput
}

export type InteractionEventUncheckedCreateInput = {
  id?: string
  interactionId: string
  type: $Enums.InteractionEventType
  x?: number | null
  y?: number | null
  scrollX?: number | null
  scrollY?: number | null
  element?: string | null
  value?: string | null
  key?: string | null
  timestamp: number
}

export type InteractionEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionEventTypeFieldUpdateOperationsInput | $Enums.InteractionEventType
  x?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  y?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollX?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollY?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  element?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.IntFieldUpdateOperationsInput | number
  interaction?: Prisma.InteractionUpdateOneRequiredWithoutEventsNestedInput
}

export type InteractionEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  interactionId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionEventTypeFieldUpdateOperationsInput | $Enums.InteractionEventType
  x?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  y?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollX?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollY?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  element?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.IntFieldUpdateOperationsInput | number
}

export type InteractionEventCreateManyInput = {
  id?: string
  interactionId: string
  type: $Enums.InteractionEventType
  x?: number | null
  y?: number | null
  scrollX?: number | null
  scrollY?: number | null
  element?: string | null
  value?: string | null
  key?: string | null
  timestamp: number
}

export type InteractionEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionEventTypeFieldUpdateOperationsInput | $Enums.InteractionEventType
  x?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  y?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollX?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollY?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  element?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.IntFieldUpdateOperationsInput | number
}

export type InteractionEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  interactionId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionEventTypeFieldUpdateOperationsInput | $Enums.InteractionEventType
  x?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  y?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollX?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollY?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  element?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.IntFieldUpdateOperationsInput | number
}

export type InteractionEventListRelationFilter = {
  every?: Prisma.InteractionEventWhereInput
  some?: Prisma.InteractionEventWhereInput
  none?: Prisma.InteractionEventWhereInput
}

export type InteractionEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type InteractionEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  scrollX?: Prisma.SortOrder
  scrollY?: Prisma.SortOrder
  element?: Prisma.SortOrder
  value?: Prisma.SortOrder
  key?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type InteractionEventAvgOrderByAggregateInput = {
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  scrollX?: Prisma.SortOrder
  scrollY?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type InteractionEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  scrollX?: Prisma.SortOrder
  scrollY?: Prisma.SortOrder
  element?: Prisma.SortOrder
  value?: Prisma.SortOrder
  key?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type InteractionEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  interactionId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  scrollX?: Prisma.SortOrder
  scrollY?: Prisma.SortOrder
  element?: Prisma.SortOrder
  value?: Prisma.SortOrder
  key?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type InteractionEventSumOrderByAggregateInput = {
  x?: Prisma.SortOrder
  y?: Prisma.SortOrder
  scrollX?: Prisma.SortOrder
  scrollY?: Prisma.SortOrder
  timestamp?: Prisma.SortOrder
}

export type InteractionEventCreateNestedManyWithoutInteractionInput = {
  create?: Prisma.XOR<Prisma.InteractionEventCreateWithoutInteractionInput, Prisma.InteractionEventUncheckedCreateWithoutInteractionInput> | Prisma.InteractionEventCreateWithoutInteractionInput[] | Prisma.InteractionEventUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.InteractionEventCreateOrConnectWithoutInteractionInput | Prisma.InteractionEventCreateOrConnectWithoutInteractionInput[]
  createMany?: Prisma.InteractionEventCreateManyInteractionInputEnvelope
  connect?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
}

export type InteractionEventUncheckedCreateNestedManyWithoutInteractionInput = {
  create?: Prisma.XOR<Prisma.InteractionEventCreateWithoutInteractionInput, Prisma.InteractionEventUncheckedCreateWithoutInteractionInput> | Prisma.InteractionEventCreateWithoutInteractionInput[] | Prisma.InteractionEventUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.InteractionEventCreateOrConnectWithoutInteractionInput | Prisma.InteractionEventCreateOrConnectWithoutInteractionInput[]
  createMany?: Prisma.InteractionEventCreateManyInteractionInputEnvelope
  connect?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
}

export type InteractionEventUpdateManyWithoutInteractionNestedInput = {
  create?: Prisma.XOR<Prisma.InteractionEventCreateWithoutInteractionInput, Prisma.InteractionEventUncheckedCreateWithoutInteractionInput> | Prisma.InteractionEventCreateWithoutInteractionInput[] | Prisma.InteractionEventUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.InteractionEventCreateOrConnectWithoutInteractionInput | Prisma.InteractionEventCreateOrConnectWithoutInteractionInput[]
  upsert?: Prisma.InteractionEventUpsertWithWhereUniqueWithoutInteractionInput | Prisma.InteractionEventUpsertWithWhereUniqueWithoutInteractionInput[]
  createMany?: Prisma.InteractionEventCreateManyInteractionInputEnvelope
  set?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  disconnect?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  delete?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  connect?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  update?: Prisma.InteractionEventUpdateWithWhereUniqueWithoutInteractionInput | Prisma.InteractionEventUpdateWithWhereUniqueWithoutInteractionInput[]
  updateMany?: Prisma.InteractionEventUpdateManyWithWhereWithoutInteractionInput | Prisma.InteractionEventUpdateManyWithWhereWithoutInteractionInput[]
  deleteMany?: Prisma.InteractionEventScalarWhereInput | Prisma.InteractionEventScalarWhereInput[]
}

export type InteractionEventUncheckedUpdateManyWithoutInteractionNestedInput = {
  create?: Prisma.XOR<Prisma.InteractionEventCreateWithoutInteractionInput, Prisma.InteractionEventUncheckedCreateWithoutInteractionInput> | Prisma.InteractionEventCreateWithoutInteractionInput[] | Prisma.InteractionEventUncheckedCreateWithoutInteractionInput[]
  connectOrCreate?: Prisma.InteractionEventCreateOrConnectWithoutInteractionInput | Prisma.InteractionEventCreateOrConnectWithoutInteractionInput[]
  upsert?: Prisma.InteractionEventUpsertWithWhereUniqueWithoutInteractionInput | Prisma.InteractionEventUpsertWithWhereUniqueWithoutInteractionInput[]
  createMany?: Prisma.InteractionEventCreateManyInteractionInputEnvelope
  set?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  disconnect?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  delete?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  connect?: Prisma.InteractionEventWhereUniqueInput | Prisma.InteractionEventWhereUniqueInput[]
  update?: Prisma.InteractionEventUpdateWithWhereUniqueWithoutInteractionInput | Prisma.InteractionEventUpdateWithWhereUniqueWithoutInteractionInput[]
  updateMany?: Prisma.InteractionEventUpdateManyWithWhereWithoutInteractionInput | Prisma.InteractionEventUpdateManyWithWhereWithoutInteractionInput[]
  deleteMany?: Prisma.InteractionEventScalarWhereInput | Prisma.InteractionEventScalarWhereInput[]
}

export type EnumInteractionEventTypeFieldUpdateOperationsInput = {
  set?: $Enums.InteractionEventType
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type InteractionEventCreateWithoutInteractionInput = {
  id?: string
  type: $Enums.InteractionEventType
  x?: number | null
  y?: number | null
  scrollX?: number | null
  scrollY?: number | null
  element?: string | null
  value?: string | null
  key?: string | null
  timestamp: number
}

export type InteractionEventUncheckedCreateWithoutInteractionInput = {
  id?: string
  type: $Enums.InteractionEventType
  x?: number | null
  y?: number | null
  scrollX?: number | null
  scrollY?: number | null
  element?: string | null
  value?: string | null
  key?: string | null
  timestamp: number
}

export type InteractionEventCreateOrConnectWithoutInteractionInput = {
  where: Prisma.InteractionEventWhereUniqueInput
  create: Prisma.XOR<Prisma.InteractionEventCreateWithoutInteractionInput, Prisma.InteractionEventUncheckedCreateWithoutInteractionInput>
}

export type InteractionEventCreateManyInteractionInputEnvelope = {
  data: Prisma.InteractionEventCreateManyInteractionInput | Prisma.InteractionEventCreateManyInteractionInput[]
  skipDuplicates?: boolean
}

export type InteractionEventUpsertWithWhereUniqueWithoutInteractionInput = {
  where: Prisma.InteractionEventWhereUniqueInput
  update: Prisma.XOR<Prisma.InteractionEventUpdateWithoutInteractionInput, Prisma.InteractionEventUncheckedUpdateWithoutInteractionInput>
  create: Prisma.XOR<Prisma.InteractionEventCreateWithoutInteractionInput, Prisma.InteractionEventUncheckedCreateWithoutInteractionInput>
}

export type InteractionEventUpdateWithWhereUniqueWithoutInteractionInput = {
  where: Prisma.InteractionEventWhereUniqueInput
  data: Prisma.XOR<Prisma.InteractionEventUpdateWithoutInteractionInput, Prisma.InteractionEventUncheckedUpdateWithoutInteractionInput>
}

export type InteractionEventUpdateManyWithWhereWithoutInteractionInput = {
  where: Prisma.InteractionEventScalarWhereInput
  data: Prisma.XOR<Prisma.InteractionEventUpdateManyMutationInput, Prisma.InteractionEventUncheckedUpdateManyWithoutInteractionInput>
}

export type InteractionEventScalarWhereInput = {
  AND?: Prisma.InteractionEventScalarWhereInput | Prisma.InteractionEventScalarWhereInput[]
  OR?: Prisma.InteractionEventScalarWhereInput[]
  NOT?: Prisma.InteractionEventScalarWhereInput | Prisma.InteractionEventScalarWhereInput[]
  id?: Prisma.StringFilter<"InteractionEvent"> | string
  interactionId?: Prisma.StringFilter<"InteractionEvent"> | string
  type?: Prisma.EnumInteractionEventTypeFilter<"InteractionEvent"> | $Enums.InteractionEventType
  x?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  y?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  scrollX?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  scrollY?: Prisma.IntNullableFilter<"InteractionEvent"> | number | null
  element?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  value?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  key?: Prisma.StringNullableFilter<"InteractionEvent"> | string | null
  timestamp?: Prisma.IntFilter<"InteractionEvent"> | number
}

export type InteractionEventCreateManyInteractionInput = {
  id?: string
  type: $Enums.InteractionEventType
  x?: number | null
  y?: number | null
  scrollX?: number | null
  scrollY?: number | null
  element?: string | null
  value?: string | null
  key?: string | null
  timestamp: number
}

export type InteractionEventUpdateWithoutInteractionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionEventTypeFieldUpdateOperationsInput | $Enums.InteractionEventType
  x?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  y?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollX?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollY?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  element?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.IntFieldUpdateOperationsInput | number
}

export type InteractionEventUncheckedUpdateWithoutInteractionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionEventTypeFieldUpdateOperationsInput | $Enums.InteractionEventType
  x?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  y?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollX?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollY?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  element?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.IntFieldUpdateOperationsInput | number
}

export type InteractionEventUncheckedUpdateManyWithoutInteractionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumInteractionEventTypeFieldUpdateOperationsInput | $Enums.InteractionEventType
  x?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  y?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollX?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  scrollY?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  element?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  value?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timestamp?: Prisma.IntFieldUpdateOperationsInput | number
}



export type InteractionEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  interactionId?: boolean
  type?: boolean
  x?: boolean
  y?: boolean
  scrollX?: boolean
  scrollY?: boolean
  element?: boolean
  value?: boolean
  key?: boolean
  timestamp?: boolean
  interaction?: boolean | Prisma.InteractionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interactionEvent"]>

export type InteractionEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  interactionId?: boolean
  type?: boolean
  x?: boolean
  y?: boolean
  scrollX?: boolean
  scrollY?: boolean
  element?: boolean
  value?: boolean
  key?: boolean
  timestamp?: boolean
  interaction?: boolean | Prisma.InteractionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interactionEvent"]>

export type InteractionEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  interactionId?: boolean
  type?: boolean
  x?: boolean
  y?: boolean
  scrollX?: boolean
  scrollY?: boolean
  element?: boolean
  value?: boolean
  key?: boolean
  timestamp?: boolean
  interaction?: boolean | Prisma.InteractionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["interactionEvent"]>

export type InteractionEventSelectScalar = {
  id?: boolean
  interactionId?: boolean
  type?: boolean
  x?: boolean
  y?: boolean
  scrollX?: boolean
  scrollY?: boolean
  element?: boolean
  value?: boolean
  key?: boolean
  timestamp?: boolean
}

export type InteractionEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "interactionId" | "type" | "x" | "y" | "scrollX" | "scrollY" | "element" | "value" | "key" | "timestamp", ExtArgs["result"]["interactionEvent"]>
export type InteractionEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interaction?: boolean | Prisma.InteractionDefaultArgs<ExtArgs>
}
export type InteractionEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interaction?: boolean | Prisma.InteractionDefaultArgs<ExtArgs>
}
export type InteractionEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interaction?: boolean | Prisma.InteractionDefaultArgs<ExtArgs>
}

export type $InteractionEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InteractionEvent"
  objects: {
    interaction: Prisma.$InteractionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    interactionId: string
    type: $Enums.InteractionEventType
    x: number | null
    y: number | null
    scrollX: number | null
    scrollY: number | null
    element: string | null
    value: string | null
    key: string | null
    timestamp: number
  }, ExtArgs["result"]["interactionEvent"]>
  composites: {}
}

export type InteractionEventGetPayload<S extends boolean | null | undefined | InteractionEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload, S>

export type InteractionEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InteractionEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InteractionEventCountAggregateInputType | true
  }

export interface InteractionEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InteractionEvent'], meta: { name: 'InteractionEvent' } }
  /**
   * Find zero or one InteractionEvent that matches the filter.
   * @param {InteractionEventFindUniqueArgs} args - Arguments to find a InteractionEvent
   * @example
   * // Get one InteractionEvent
   * const interactionEvent = await prisma.interactionEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InteractionEventFindUniqueArgs>(args: Prisma.SelectSubset<T, InteractionEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InteractionEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InteractionEventFindUniqueOrThrowArgs} args - Arguments to find a InteractionEvent
   * @example
   * // Get one InteractionEvent
   * const interactionEvent = await prisma.interactionEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InteractionEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InteractionEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InteractionEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionEventFindFirstArgs} args - Arguments to find a InteractionEvent
   * @example
   * // Get one InteractionEvent
   * const interactionEvent = await prisma.interactionEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InteractionEventFindFirstArgs>(args?: Prisma.SelectSubset<T, InteractionEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InteractionEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionEventFindFirstOrThrowArgs} args - Arguments to find a InteractionEvent
   * @example
   * // Get one InteractionEvent
   * const interactionEvent = await prisma.interactionEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InteractionEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InteractionEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InteractionEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InteractionEvents
   * const interactionEvents = await prisma.interactionEvent.findMany()
   * 
   * // Get first 10 InteractionEvents
   * const interactionEvents = await prisma.interactionEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const interactionEventWithIdOnly = await prisma.interactionEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InteractionEventFindManyArgs>(args?: Prisma.SelectSubset<T, InteractionEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InteractionEvent.
   * @param {InteractionEventCreateArgs} args - Arguments to create a InteractionEvent.
   * @example
   * // Create one InteractionEvent
   * const InteractionEvent = await prisma.interactionEvent.create({
   *   data: {
   *     // ... data to create a InteractionEvent
   *   }
   * })
   * 
   */
  create<T extends InteractionEventCreateArgs>(args: Prisma.SelectSubset<T, InteractionEventCreateArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InteractionEvents.
   * @param {InteractionEventCreateManyArgs} args - Arguments to create many InteractionEvents.
   * @example
   * // Create many InteractionEvents
   * const interactionEvent = await prisma.interactionEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InteractionEventCreateManyArgs>(args?: Prisma.SelectSubset<T, InteractionEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InteractionEvents and returns the data saved in the database.
   * @param {InteractionEventCreateManyAndReturnArgs} args - Arguments to create many InteractionEvents.
   * @example
   * // Create many InteractionEvents
   * const interactionEvent = await prisma.interactionEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InteractionEvents and only return the `id`
   * const interactionEventWithIdOnly = await prisma.interactionEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InteractionEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InteractionEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InteractionEvent.
   * @param {InteractionEventDeleteArgs} args - Arguments to delete one InteractionEvent.
   * @example
   * // Delete one InteractionEvent
   * const InteractionEvent = await prisma.interactionEvent.delete({
   *   where: {
   *     // ... filter to delete one InteractionEvent
   *   }
   * })
   * 
   */
  delete<T extends InteractionEventDeleteArgs>(args: Prisma.SelectSubset<T, InteractionEventDeleteArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InteractionEvent.
   * @param {InteractionEventUpdateArgs} args - Arguments to update one InteractionEvent.
   * @example
   * // Update one InteractionEvent
   * const interactionEvent = await prisma.interactionEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InteractionEventUpdateArgs>(args: Prisma.SelectSubset<T, InteractionEventUpdateArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InteractionEvents.
   * @param {InteractionEventDeleteManyArgs} args - Arguments to filter InteractionEvents to delete.
   * @example
   * // Delete a few InteractionEvents
   * const { count } = await prisma.interactionEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InteractionEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, InteractionEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InteractionEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InteractionEvents
   * const interactionEvent = await prisma.interactionEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InteractionEventUpdateManyArgs>(args: Prisma.SelectSubset<T, InteractionEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InteractionEvents and returns the data updated in the database.
   * @param {InteractionEventUpdateManyAndReturnArgs} args - Arguments to update many InteractionEvents.
   * @example
   * // Update many InteractionEvents
   * const interactionEvent = await prisma.interactionEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InteractionEvents and only return the `id`
   * const interactionEventWithIdOnly = await prisma.interactionEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InteractionEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InteractionEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InteractionEvent.
   * @param {InteractionEventUpsertArgs} args - Arguments to update or create a InteractionEvent.
   * @example
   * // Update or create a InteractionEvent
   * const interactionEvent = await prisma.interactionEvent.upsert({
   *   create: {
   *     // ... data to create a InteractionEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InteractionEvent we want to update
   *   }
   * })
   */
  upsert<T extends InteractionEventUpsertArgs>(args: Prisma.SelectSubset<T, InteractionEventUpsertArgs<ExtArgs>>): Prisma.Prisma__InteractionEventClient<runtime.Types.Result.GetResult<Prisma.$InteractionEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InteractionEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionEventCountArgs} args - Arguments to filter InteractionEvents to count.
   * @example
   * // Count the number of InteractionEvents
   * const count = await prisma.interactionEvent.count({
   *   where: {
   *     // ... the filter for the InteractionEvents we want to count
   *   }
   * })
  **/
  count<T extends InteractionEventCountArgs>(
    args?: Prisma.Subset<T, InteractionEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InteractionEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InteractionEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InteractionEventAggregateArgs>(args: Prisma.Subset<T, InteractionEventAggregateArgs>): Prisma.PrismaPromise<GetInteractionEventAggregateType<T>>

  /**
   * Group by InteractionEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InteractionEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InteractionEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InteractionEventGroupByArgs['orderBy'] }
      : { orderBy?: InteractionEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InteractionEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInteractionEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InteractionEvent model
 */
readonly fields: InteractionEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InteractionEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InteractionEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  interaction<T extends Prisma.InteractionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.InteractionDefaultArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InteractionEvent model
 */
export interface InteractionEventFieldRefs {
  readonly id: Prisma.FieldRef<"InteractionEvent", 'String'>
  readonly interactionId: Prisma.FieldRef<"InteractionEvent", 'String'>
  readonly type: Prisma.FieldRef<"InteractionEvent", 'InteractionEventType'>
  readonly x: Prisma.FieldRef<"InteractionEvent", 'Int'>
  readonly y: Prisma.FieldRef<"InteractionEvent", 'Int'>
  readonly scrollX: Prisma.FieldRef<"InteractionEvent", 'Int'>
  readonly scrollY: Prisma.FieldRef<"InteractionEvent", 'Int'>
  readonly element: Prisma.FieldRef<"InteractionEvent", 'String'>
  readonly value: Prisma.FieldRef<"InteractionEvent", 'String'>
  readonly key: Prisma.FieldRef<"InteractionEvent", 'String'>
  readonly timestamp: Prisma.FieldRef<"InteractionEvent", 'Int'>
}
    

// Custom InputTypes
/**
 * InteractionEvent findUnique
 */
export type InteractionEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * Filter, which InteractionEvent to fetch.
   */
  where: Prisma.InteractionEventWhereUniqueInput
}

/**
 * InteractionEvent findUniqueOrThrow
 */
export type InteractionEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * Filter, which InteractionEvent to fetch.
   */
  where: Prisma.InteractionEventWhereUniqueInput
}

/**
 * InteractionEvent findFirst
 */
export type InteractionEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * Filter, which InteractionEvent to fetch.
   */
  where?: Prisma.InteractionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InteractionEvents to fetch.
   */
  orderBy?: Prisma.InteractionEventOrderByWithRelationInput | Prisma.InteractionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InteractionEvents.
   */
  cursor?: Prisma.InteractionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InteractionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InteractionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InteractionEvents.
   */
  distinct?: Prisma.InteractionEventScalarFieldEnum | Prisma.InteractionEventScalarFieldEnum[]
}

/**
 * InteractionEvent findFirstOrThrow
 */
export type InteractionEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * Filter, which InteractionEvent to fetch.
   */
  where?: Prisma.InteractionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InteractionEvents to fetch.
   */
  orderBy?: Prisma.InteractionEventOrderByWithRelationInput | Prisma.InteractionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InteractionEvents.
   */
  cursor?: Prisma.InteractionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InteractionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InteractionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InteractionEvents.
   */
  distinct?: Prisma.InteractionEventScalarFieldEnum | Prisma.InteractionEventScalarFieldEnum[]
}

/**
 * InteractionEvent findMany
 */
export type InteractionEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * Filter, which InteractionEvents to fetch.
   */
  where?: Prisma.InteractionEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InteractionEvents to fetch.
   */
  orderBy?: Prisma.InteractionEventOrderByWithRelationInput | Prisma.InteractionEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InteractionEvents.
   */
  cursor?: Prisma.InteractionEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InteractionEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InteractionEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InteractionEvents.
   */
  distinct?: Prisma.InteractionEventScalarFieldEnum | Prisma.InteractionEventScalarFieldEnum[]
}

/**
 * InteractionEvent create
 */
export type InteractionEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * The data needed to create a InteractionEvent.
   */
  data: Prisma.XOR<Prisma.InteractionEventCreateInput, Prisma.InteractionEventUncheckedCreateInput>
}

/**
 * InteractionEvent createMany
 */
export type InteractionEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InteractionEvents.
   */
  data: Prisma.InteractionEventCreateManyInput | Prisma.InteractionEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InteractionEvent createManyAndReturn
 */
export type InteractionEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * The data used to create many InteractionEvents.
   */
  data: Prisma.InteractionEventCreateManyInput | Prisma.InteractionEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InteractionEvent update
 */
export type InteractionEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * The data needed to update a InteractionEvent.
   */
  data: Prisma.XOR<Prisma.InteractionEventUpdateInput, Prisma.InteractionEventUncheckedUpdateInput>
  /**
   * Choose, which InteractionEvent to update.
   */
  where: Prisma.InteractionEventWhereUniqueInput
}

/**
 * InteractionEvent updateMany
 */
export type InteractionEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InteractionEvents.
   */
  data: Prisma.XOR<Prisma.InteractionEventUpdateManyMutationInput, Prisma.InteractionEventUncheckedUpdateManyInput>
  /**
   * Filter which InteractionEvents to update
   */
  where?: Prisma.InteractionEventWhereInput
  /**
   * Limit how many InteractionEvents to update.
   */
  limit?: number
}

/**
 * InteractionEvent updateManyAndReturn
 */
export type InteractionEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * The data used to update InteractionEvents.
   */
  data: Prisma.XOR<Prisma.InteractionEventUpdateManyMutationInput, Prisma.InteractionEventUncheckedUpdateManyInput>
  /**
   * Filter which InteractionEvents to update
   */
  where?: Prisma.InteractionEventWhereInput
  /**
   * Limit how many InteractionEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InteractionEvent upsert
 */
export type InteractionEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * The filter to search for the InteractionEvent to update in case it exists.
   */
  where: Prisma.InteractionEventWhereUniqueInput
  /**
   * In case the InteractionEvent found by the `where` argument doesn't exist, create a new InteractionEvent with this data.
   */
  create: Prisma.XOR<Prisma.InteractionEventCreateInput, Prisma.InteractionEventUncheckedCreateInput>
  /**
   * In case the InteractionEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InteractionEventUpdateInput, Prisma.InteractionEventUncheckedUpdateInput>
}

/**
 * InteractionEvent delete
 */
export type InteractionEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
  /**
   * Filter which InteractionEvent to delete.
   */
  where: Prisma.InteractionEventWhereUniqueInput
}

/**
 * InteractionEvent deleteMany
 */
export type InteractionEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InteractionEvents to delete
   */
  where?: Prisma.InteractionEventWhereInput
  /**
   * Limit how many InteractionEvents to delete.
   */
  limit?: number
}

/**
 * InteractionEvent without action
 */
export type InteractionEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InteractionEvent
   */
  select?: Prisma.InteractionEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InteractionEvent
   */
  omit?: Prisma.InteractionEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionEventInclude<ExtArgs> | null
}
