
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PageSnapshot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PageSnapshot
 * 
 */
export type PageSnapshotModel = runtime.Types.Result.DefaultSelection<Prisma.$PageSnapshotPayload>

export type AggregatePageSnapshot = {
  _count: PageSnapshotCountAggregateOutputType | null
  _avg: PageSnapshotAvgAggregateOutputType | null
  _sum: PageSnapshotSumAggregateOutputType | null
  _min: PageSnapshotMinAggregateOutputType | null
  _max: PageSnapshotMaxAggregateOutputType | null
}

export type PageSnapshotAvgAggregateOutputType = {
  version: number | null
}

export type PageSnapshotSumAggregateOutputType = {
  version: number | null
}

export type PageSnapshotMinAggregateOutputType = {
  id: string | null
  pagePath: string | null
  siteId: string | null
  content: string | null
  version: number | null
  recordedOn: Date | null
}

export type PageSnapshotMaxAggregateOutputType = {
  id: string | null
  pagePath: string | null
  siteId: string | null
  content: string | null
  version: number | null
  recordedOn: Date | null
}

export type PageSnapshotCountAggregateOutputType = {
  id: number
  pagePath: number
  siteId: number
  content: number
  version: number
  recordedOn: number
  _all: number
}


export type PageSnapshotAvgAggregateInputType = {
  version?: true
}

export type PageSnapshotSumAggregateInputType = {
  version?: true
}

export type PageSnapshotMinAggregateInputType = {
  id?: true
  pagePath?: true
  siteId?: true
  content?: true
  version?: true
  recordedOn?: true
}

export type PageSnapshotMaxAggregateInputType = {
  id?: true
  pagePath?: true
  siteId?: true
  content?: true
  version?: true
  recordedOn?: true
}

export type PageSnapshotCountAggregateInputType = {
  id?: true
  pagePath?: true
  siteId?: true
  content?: true
  version?: true
  recordedOn?: true
  _all?: true
}

export type PageSnapshotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageSnapshot to aggregate.
   */
  where?: Prisma.PageSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageSnapshots to fetch.
   */
  orderBy?: Prisma.PageSnapshotOrderByWithRelationInput | Prisma.PageSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PageSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PageSnapshots
  **/
  _count?: true | PageSnapshotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PageSnapshotAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PageSnapshotSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PageSnapshotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PageSnapshotMaxAggregateInputType
}

export type GetPageSnapshotAggregateType<T extends PageSnapshotAggregateArgs> = {
      [P in keyof T & keyof AggregatePageSnapshot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePageSnapshot[P]>
    : Prisma.GetScalarType<T[P], AggregatePageSnapshot[P]>
}




export type PageSnapshotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PageSnapshotWhereInput
  orderBy?: Prisma.PageSnapshotOrderByWithAggregationInput | Prisma.PageSnapshotOrderByWithAggregationInput[]
  by: Prisma.PageSnapshotScalarFieldEnum[] | Prisma.PageSnapshotScalarFieldEnum
  having?: Prisma.PageSnapshotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PageSnapshotCountAggregateInputType | true
  _avg?: PageSnapshotAvgAggregateInputType
  _sum?: PageSnapshotSumAggregateInputType
  _min?: PageSnapshotMinAggregateInputType
  _max?: PageSnapshotMaxAggregateInputType
}

export type PageSnapshotGroupByOutputType = {
  id: string
  pagePath: string
  siteId: string
  content: string
  version: number
  recordedOn: Date
  _count: PageSnapshotCountAggregateOutputType | null
  _avg: PageSnapshotAvgAggregateOutputType | null
  _sum: PageSnapshotSumAggregateOutputType | null
  _min: PageSnapshotMinAggregateOutputType | null
  _max: PageSnapshotMaxAggregateOutputType | null
}

export type GetPageSnapshotGroupByPayload<T extends PageSnapshotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PageSnapshotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PageSnapshotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PageSnapshotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PageSnapshotGroupByOutputType[P]>
      }
    >
  >



export type PageSnapshotWhereInput = {
  AND?: Prisma.PageSnapshotWhereInput | Prisma.PageSnapshotWhereInput[]
  OR?: Prisma.PageSnapshotWhereInput[]
  NOT?: Prisma.PageSnapshotWhereInput | Prisma.PageSnapshotWhereInput[]
  id?: Prisma.StringFilter<"PageSnapshot"> | string
  pagePath?: Prisma.StringFilter<"PageSnapshot"> | string
  siteId?: Prisma.StringFilter<"PageSnapshot"> | string
  content?: Prisma.StringFilter<"PageSnapshot"> | string
  version?: Prisma.IntFilter<"PageSnapshot"> | number
  recordedOn?: Prisma.DateTimeFilter<"PageSnapshot"> | Date | string
  interactions?: Prisma.InteractionListRelationFilter
}

export type PageSnapshotOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pagePath?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  recordedOn?: Prisma.SortOrder
  interactions?: Prisma.InteractionOrderByRelationAggregateInput
}

export type PageSnapshotWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PageSnapshotWhereInput | Prisma.PageSnapshotWhereInput[]
  OR?: Prisma.PageSnapshotWhereInput[]
  NOT?: Prisma.PageSnapshotWhereInput | Prisma.PageSnapshotWhereInput[]
  pagePath?: Prisma.StringFilter<"PageSnapshot"> | string
  siteId?: Prisma.StringFilter<"PageSnapshot"> | string
  content?: Prisma.StringFilter<"PageSnapshot"> | string
  version?: Prisma.IntFilter<"PageSnapshot"> | number
  recordedOn?: Prisma.DateTimeFilter<"PageSnapshot"> | Date | string
  interactions?: Prisma.InteractionListRelationFilter
}, "id">

export type PageSnapshotOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pagePath?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  recordedOn?: Prisma.SortOrder
  _count?: Prisma.PageSnapshotCountOrderByAggregateInput
  _avg?: Prisma.PageSnapshotAvgOrderByAggregateInput
  _max?: Prisma.PageSnapshotMaxOrderByAggregateInput
  _min?: Prisma.PageSnapshotMinOrderByAggregateInput
  _sum?: Prisma.PageSnapshotSumOrderByAggregateInput
}

export type PageSnapshotScalarWhereWithAggregatesInput = {
  AND?: Prisma.PageSnapshotScalarWhereWithAggregatesInput | Prisma.PageSnapshotScalarWhereWithAggregatesInput[]
  OR?: Prisma.PageSnapshotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PageSnapshotScalarWhereWithAggregatesInput | Prisma.PageSnapshotScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PageSnapshot"> | string
  pagePath?: Prisma.StringWithAggregatesFilter<"PageSnapshot"> | string
  siteId?: Prisma.StringWithAggregatesFilter<"PageSnapshot"> | string
  content?: Prisma.StringWithAggregatesFilter<"PageSnapshot"> | string
  version?: Prisma.IntWithAggregatesFilter<"PageSnapshot"> | number
  recordedOn?: Prisma.DateTimeWithAggregatesFilter<"PageSnapshot"> | Date | string
}

export type PageSnapshotCreateInput = {
  id?: string
  pagePath: string
  siteId: string
  content: string
  version?: number
  recordedOn?: Date | string
  interactions?: Prisma.InteractionCreateNestedManyWithoutPageInput
}

export type PageSnapshotUncheckedCreateInput = {
  id?: string
  pagePath: string
  siteId: string
  content: string
  version?: number
  recordedOn?: Date | string
  interactions?: Prisma.InteractionUncheckedCreateNestedManyWithoutPageInput
}

export type PageSnapshotUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pagePath?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  recordedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  interactions?: Prisma.InteractionUpdateManyWithoutPageNestedInput
}

export type PageSnapshotUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pagePath?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  recordedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  interactions?: Prisma.InteractionUncheckedUpdateManyWithoutPageNestedInput
}

export type PageSnapshotCreateManyInput = {
  id?: string
  pagePath: string
  siteId: string
  content: string
  version?: number
  recordedOn?: Date | string
}

export type PageSnapshotUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pagePath?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  recordedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageSnapshotUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pagePath?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  recordedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageSnapshotCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pagePath?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  recordedOn?: Prisma.SortOrder
}

export type PageSnapshotAvgOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type PageSnapshotMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pagePath?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  recordedOn?: Prisma.SortOrder
}

export type PageSnapshotMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pagePath?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  content?: Prisma.SortOrder
  version?: Prisma.SortOrder
  recordedOn?: Prisma.SortOrder
}

export type PageSnapshotSumOrderByAggregateInput = {
  version?: Prisma.SortOrder
}

export type PageSnapshotNullableScalarRelationFilter = {
  is?: Prisma.PageSnapshotWhereInput | null
  isNot?: Prisma.PageSnapshotWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type PageSnapshotCreateNestedOneWithoutInteractionsInput = {
  create?: Prisma.XOR<Prisma.PageSnapshotCreateWithoutInteractionsInput, Prisma.PageSnapshotUncheckedCreateWithoutInteractionsInput>
  connectOrCreate?: Prisma.PageSnapshotCreateOrConnectWithoutInteractionsInput
  connect?: Prisma.PageSnapshotWhereUniqueInput
}

export type PageSnapshotUpdateOneWithoutInteractionsNestedInput = {
  create?: Prisma.XOR<Prisma.PageSnapshotCreateWithoutInteractionsInput, Prisma.PageSnapshotUncheckedCreateWithoutInteractionsInput>
  connectOrCreate?: Prisma.PageSnapshotCreateOrConnectWithoutInteractionsInput
  upsert?: Prisma.PageSnapshotUpsertWithoutInteractionsInput
  disconnect?: Prisma.PageSnapshotWhereInput | boolean
  delete?: Prisma.PageSnapshotWhereInput | boolean
  connect?: Prisma.PageSnapshotWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PageSnapshotUpdateToOneWithWhereWithoutInteractionsInput, Prisma.PageSnapshotUpdateWithoutInteractionsInput>, Prisma.PageSnapshotUncheckedUpdateWithoutInteractionsInput>
}

export type PageSnapshotCreateWithoutInteractionsInput = {
  id?: string
  pagePath: string
  siteId: string
  content: string
  version?: number
  recordedOn?: Date | string
}

export type PageSnapshotUncheckedCreateWithoutInteractionsInput = {
  id?: string
  pagePath: string
  siteId: string
  content: string
  version?: number
  recordedOn?: Date | string
}

export type PageSnapshotCreateOrConnectWithoutInteractionsInput = {
  where: Prisma.PageSnapshotWhereUniqueInput
  create: Prisma.XOR<Prisma.PageSnapshotCreateWithoutInteractionsInput, Prisma.PageSnapshotUncheckedCreateWithoutInteractionsInput>
}

export type PageSnapshotUpsertWithoutInteractionsInput = {
  update: Prisma.XOR<Prisma.PageSnapshotUpdateWithoutInteractionsInput, Prisma.PageSnapshotUncheckedUpdateWithoutInteractionsInput>
  create: Prisma.XOR<Prisma.PageSnapshotCreateWithoutInteractionsInput, Prisma.PageSnapshotUncheckedCreateWithoutInteractionsInput>
  where?: Prisma.PageSnapshotWhereInput
}

export type PageSnapshotUpdateToOneWithWhereWithoutInteractionsInput = {
  where?: Prisma.PageSnapshotWhereInput
  data: Prisma.XOR<Prisma.PageSnapshotUpdateWithoutInteractionsInput, Prisma.PageSnapshotUncheckedUpdateWithoutInteractionsInput>
}

export type PageSnapshotUpdateWithoutInteractionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pagePath?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  recordedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PageSnapshotUncheckedUpdateWithoutInteractionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pagePath?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.StringFieldUpdateOperationsInput | string
  version?: Prisma.IntFieldUpdateOperationsInput | number
  recordedOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type PageSnapshotCountOutputType
 */

export type PageSnapshotCountOutputType = {
  interactions: number
}

export type PageSnapshotCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interactions?: boolean | PageSnapshotCountOutputTypeCountInteractionsArgs
}

/**
 * PageSnapshotCountOutputType without action
 */
export type PageSnapshotCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshotCountOutputType
   */
  select?: Prisma.PageSnapshotCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PageSnapshotCountOutputType without action
 */
export type PageSnapshotCountOutputTypeCountInteractionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InteractionWhereInput
}


export type PageSnapshotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pagePath?: boolean
  siteId?: boolean
  content?: boolean
  version?: boolean
  recordedOn?: boolean
  interactions?: boolean | Prisma.PageSnapshot$interactionsArgs<ExtArgs>
  _count?: boolean | Prisma.PageSnapshotCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pageSnapshot"]>

export type PageSnapshotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pagePath?: boolean
  siteId?: boolean
  content?: boolean
  version?: boolean
  recordedOn?: boolean
}, ExtArgs["result"]["pageSnapshot"]>

export type PageSnapshotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pagePath?: boolean
  siteId?: boolean
  content?: boolean
  version?: boolean
  recordedOn?: boolean
}, ExtArgs["result"]["pageSnapshot"]>

export type PageSnapshotSelectScalar = {
  id?: boolean
  pagePath?: boolean
  siteId?: boolean
  content?: boolean
  version?: boolean
  recordedOn?: boolean
}

export type PageSnapshotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pagePath" | "siteId" | "content" | "version" | "recordedOn", ExtArgs["result"]["pageSnapshot"]>
export type PageSnapshotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  interactions?: boolean | Prisma.PageSnapshot$interactionsArgs<ExtArgs>
  _count?: boolean | Prisma.PageSnapshotCountOutputTypeDefaultArgs<ExtArgs>
}
export type PageSnapshotIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type PageSnapshotIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $PageSnapshotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PageSnapshot"
  objects: {
    interactions: Prisma.$InteractionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pagePath: string
    siteId: string
    content: string
    version: number
    recordedOn: Date
  }, ExtArgs["result"]["pageSnapshot"]>
  composites: {}
}

export type PageSnapshotGetPayload<S extends boolean | null | undefined | PageSnapshotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload, S>

export type PageSnapshotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PageSnapshotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PageSnapshotCountAggregateInputType | true
  }

export interface PageSnapshotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PageSnapshot'], meta: { name: 'PageSnapshot' } }
  /**
   * Find zero or one PageSnapshot that matches the filter.
   * @param {PageSnapshotFindUniqueArgs} args - Arguments to find a PageSnapshot
   * @example
   * // Get one PageSnapshot
   * const pageSnapshot = await prisma.pageSnapshot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PageSnapshotFindUniqueArgs>(args: Prisma.SelectSubset<T, PageSnapshotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PageSnapshot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PageSnapshotFindUniqueOrThrowArgs} args - Arguments to find a PageSnapshot
   * @example
   * // Get one PageSnapshot
   * const pageSnapshot = await prisma.pageSnapshot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PageSnapshotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PageSnapshotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageSnapshot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageSnapshotFindFirstArgs} args - Arguments to find a PageSnapshot
   * @example
   * // Get one PageSnapshot
   * const pageSnapshot = await prisma.pageSnapshot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PageSnapshotFindFirstArgs>(args?: Prisma.SelectSubset<T, PageSnapshotFindFirstArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PageSnapshot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageSnapshotFindFirstOrThrowArgs} args - Arguments to find a PageSnapshot
   * @example
   * // Get one PageSnapshot
   * const pageSnapshot = await prisma.pageSnapshot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PageSnapshotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PageSnapshotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PageSnapshots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageSnapshotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PageSnapshots
   * const pageSnapshots = await prisma.pageSnapshot.findMany()
   * 
   * // Get first 10 PageSnapshots
   * const pageSnapshots = await prisma.pageSnapshot.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pageSnapshotWithIdOnly = await prisma.pageSnapshot.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PageSnapshotFindManyArgs>(args?: Prisma.SelectSubset<T, PageSnapshotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PageSnapshot.
   * @param {PageSnapshotCreateArgs} args - Arguments to create a PageSnapshot.
   * @example
   * // Create one PageSnapshot
   * const PageSnapshot = await prisma.pageSnapshot.create({
   *   data: {
   *     // ... data to create a PageSnapshot
   *   }
   * })
   * 
   */
  create<T extends PageSnapshotCreateArgs>(args: Prisma.SelectSubset<T, PageSnapshotCreateArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PageSnapshots.
   * @param {PageSnapshotCreateManyArgs} args - Arguments to create many PageSnapshots.
   * @example
   * // Create many PageSnapshots
   * const pageSnapshot = await prisma.pageSnapshot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PageSnapshotCreateManyArgs>(args?: Prisma.SelectSubset<T, PageSnapshotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PageSnapshots and returns the data saved in the database.
   * @param {PageSnapshotCreateManyAndReturnArgs} args - Arguments to create many PageSnapshots.
   * @example
   * // Create many PageSnapshots
   * const pageSnapshot = await prisma.pageSnapshot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PageSnapshots and only return the `id`
   * const pageSnapshotWithIdOnly = await prisma.pageSnapshot.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PageSnapshotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PageSnapshotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PageSnapshot.
   * @param {PageSnapshotDeleteArgs} args - Arguments to delete one PageSnapshot.
   * @example
   * // Delete one PageSnapshot
   * const PageSnapshot = await prisma.pageSnapshot.delete({
   *   where: {
   *     // ... filter to delete one PageSnapshot
   *   }
   * })
   * 
   */
  delete<T extends PageSnapshotDeleteArgs>(args: Prisma.SelectSubset<T, PageSnapshotDeleteArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PageSnapshot.
   * @param {PageSnapshotUpdateArgs} args - Arguments to update one PageSnapshot.
   * @example
   * // Update one PageSnapshot
   * const pageSnapshot = await prisma.pageSnapshot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PageSnapshotUpdateArgs>(args: Prisma.SelectSubset<T, PageSnapshotUpdateArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PageSnapshots.
   * @param {PageSnapshotDeleteManyArgs} args - Arguments to filter PageSnapshots to delete.
   * @example
   * // Delete a few PageSnapshots
   * const { count } = await prisma.pageSnapshot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PageSnapshotDeleteManyArgs>(args?: Prisma.SelectSubset<T, PageSnapshotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageSnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageSnapshotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PageSnapshots
   * const pageSnapshot = await prisma.pageSnapshot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PageSnapshotUpdateManyArgs>(args: Prisma.SelectSubset<T, PageSnapshotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PageSnapshots and returns the data updated in the database.
   * @param {PageSnapshotUpdateManyAndReturnArgs} args - Arguments to update many PageSnapshots.
   * @example
   * // Update many PageSnapshots
   * const pageSnapshot = await prisma.pageSnapshot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PageSnapshots and only return the `id`
   * const pageSnapshotWithIdOnly = await prisma.pageSnapshot.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PageSnapshotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PageSnapshotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PageSnapshot.
   * @param {PageSnapshotUpsertArgs} args - Arguments to update or create a PageSnapshot.
   * @example
   * // Update or create a PageSnapshot
   * const pageSnapshot = await prisma.pageSnapshot.upsert({
   *   create: {
   *     // ... data to create a PageSnapshot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PageSnapshot we want to update
   *   }
   * })
   */
  upsert<T extends PageSnapshotUpsertArgs>(args: Prisma.SelectSubset<T, PageSnapshotUpsertArgs<ExtArgs>>): Prisma.Prisma__PageSnapshotClient<runtime.Types.Result.GetResult<Prisma.$PageSnapshotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PageSnapshots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageSnapshotCountArgs} args - Arguments to filter PageSnapshots to count.
   * @example
   * // Count the number of PageSnapshots
   * const count = await prisma.pageSnapshot.count({
   *   where: {
   *     // ... the filter for the PageSnapshots we want to count
   *   }
   * })
  **/
  count<T extends PageSnapshotCountArgs>(
    args?: Prisma.Subset<T, PageSnapshotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PageSnapshotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PageSnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageSnapshotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PageSnapshotAggregateArgs>(args: Prisma.Subset<T, PageSnapshotAggregateArgs>): Prisma.PrismaPromise<GetPageSnapshotAggregateType<T>>

  /**
   * Group by PageSnapshot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PageSnapshotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PageSnapshotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PageSnapshotGroupByArgs['orderBy'] }
      : { orderBy?: PageSnapshotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PageSnapshotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPageSnapshotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PageSnapshot model
 */
readonly fields: PageSnapshotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PageSnapshot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PageSnapshotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  interactions<T extends Prisma.PageSnapshot$interactionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PageSnapshot$interactionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PageSnapshot model
 */
export interface PageSnapshotFieldRefs {
  readonly id: Prisma.FieldRef<"PageSnapshot", 'String'>
  readonly pagePath: Prisma.FieldRef<"PageSnapshot", 'String'>
  readonly siteId: Prisma.FieldRef<"PageSnapshot", 'String'>
  readonly content: Prisma.FieldRef<"PageSnapshot", 'String'>
  readonly version: Prisma.FieldRef<"PageSnapshot", 'Int'>
  readonly recordedOn: Prisma.FieldRef<"PageSnapshot", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PageSnapshot findUnique
 */
export type PageSnapshotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * Filter, which PageSnapshot to fetch.
   */
  where: Prisma.PageSnapshotWhereUniqueInput
}

/**
 * PageSnapshot findUniqueOrThrow
 */
export type PageSnapshotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * Filter, which PageSnapshot to fetch.
   */
  where: Prisma.PageSnapshotWhereUniqueInput
}

/**
 * PageSnapshot findFirst
 */
export type PageSnapshotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * Filter, which PageSnapshot to fetch.
   */
  where?: Prisma.PageSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageSnapshots to fetch.
   */
  orderBy?: Prisma.PageSnapshotOrderByWithRelationInput | Prisma.PageSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageSnapshots.
   */
  cursor?: Prisma.PageSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageSnapshots.
   */
  distinct?: Prisma.PageSnapshotScalarFieldEnum | Prisma.PageSnapshotScalarFieldEnum[]
}

/**
 * PageSnapshot findFirstOrThrow
 */
export type PageSnapshotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * Filter, which PageSnapshot to fetch.
   */
  where?: Prisma.PageSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageSnapshots to fetch.
   */
  orderBy?: Prisma.PageSnapshotOrderByWithRelationInput | Prisma.PageSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PageSnapshots.
   */
  cursor?: Prisma.PageSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageSnapshots.
   */
  distinct?: Prisma.PageSnapshotScalarFieldEnum | Prisma.PageSnapshotScalarFieldEnum[]
}

/**
 * PageSnapshot findMany
 */
export type PageSnapshotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * Filter, which PageSnapshots to fetch.
   */
  where?: Prisma.PageSnapshotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PageSnapshots to fetch.
   */
  orderBy?: Prisma.PageSnapshotOrderByWithRelationInput | Prisma.PageSnapshotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PageSnapshots.
   */
  cursor?: Prisma.PageSnapshotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PageSnapshots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PageSnapshots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PageSnapshots.
   */
  distinct?: Prisma.PageSnapshotScalarFieldEnum | Prisma.PageSnapshotScalarFieldEnum[]
}

/**
 * PageSnapshot create
 */
export type PageSnapshotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * The data needed to create a PageSnapshot.
   */
  data: Prisma.XOR<Prisma.PageSnapshotCreateInput, Prisma.PageSnapshotUncheckedCreateInput>
}

/**
 * PageSnapshot createMany
 */
export type PageSnapshotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PageSnapshots.
   */
  data: Prisma.PageSnapshotCreateManyInput | Prisma.PageSnapshotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PageSnapshot createManyAndReturn
 */
export type PageSnapshotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * The data used to create many PageSnapshots.
   */
  data: Prisma.PageSnapshotCreateManyInput | Prisma.PageSnapshotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PageSnapshot update
 */
export type PageSnapshotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * The data needed to update a PageSnapshot.
   */
  data: Prisma.XOR<Prisma.PageSnapshotUpdateInput, Prisma.PageSnapshotUncheckedUpdateInput>
  /**
   * Choose, which PageSnapshot to update.
   */
  where: Prisma.PageSnapshotWhereUniqueInput
}

/**
 * PageSnapshot updateMany
 */
export type PageSnapshotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PageSnapshots.
   */
  data: Prisma.XOR<Prisma.PageSnapshotUpdateManyMutationInput, Prisma.PageSnapshotUncheckedUpdateManyInput>
  /**
   * Filter which PageSnapshots to update
   */
  where?: Prisma.PageSnapshotWhereInput
  /**
   * Limit how many PageSnapshots to update.
   */
  limit?: number
}

/**
 * PageSnapshot updateManyAndReturn
 */
export type PageSnapshotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * The data used to update PageSnapshots.
   */
  data: Prisma.XOR<Prisma.PageSnapshotUpdateManyMutationInput, Prisma.PageSnapshotUncheckedUpdateManyInput>
  /**
   * Filter which PageSnapshots to update
   */
  where?: Prisma.PageSnapshotWhereInput
  /**
   * Limit how many PageSnapshots to update.
   */
  limit?: number
}

/**
 * PageSnapshot upsert
 */
export type PageSnapshotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * The filter to search for the PageSnapshot to update in case it exists.
   */
  where: Prisma.PageSnapshotWhereUniqueInput
  /**
   * In case the PageSnapshot found by the `where` argument doesn't exist, create a new PageSnapshot with this data.
   */
  create: Prisma.XOR<Prisma.PageSnapshotCreateInput, Prisma.PageSnapshotUncheckedCreateInput>
  /**
   * In case the PageSnapshot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PageSnapshotUpdateInput, Prisma.PageSnapshotUncheckedUpdateInput>
}

/**
 * PageSnapshot delete
 */
export type PageSnapshotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
  /**
   * Filter which PageSnapshot to delete.
   */
  where: Prisma.PageSnapshotWhereUniqueInput
}

/**
 * PageSnapshot deleteMany
 */
export type PageSnapshotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PageSnapshots to delete
   */
  where?: Prisma.PageSnapshotWhereInput
  /**
   * Limit how many PageSnapshots to delete.
   */
  limit?: number
}

/**
 * PageSnapshot.interactions
 */
export type PageSnapshot$interactionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  where?: Prisma.InteractionWhereInput
  orderBy?: Prisma.InteractionOrderByWithRelationInput | Prisma.InteractionOrderByWithRelationInput[]
  cursor?: Prisma.InteractionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.InteractionScalarFieldEnum | Prisma.InteractionScalarFieldEnum[]
}

/**
 * PageSnapshot without action
 */
export type PageSnapshotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PageSnapshot
   */
  select?: Prisma.PageSnapshotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PageSnapshot
   */
  omit?: Prisma.PageSnapshotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PageSnapshotInclude<ExtArgs> | null
}
