
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SnapshotWeb` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SnapshotWeb
 * 
 */
export type SnapshotWebModel = runtime.Types.Result.DefaultSelection<Prisma.$SnapshotWebPayload>

export type AggregateSnapshotWeb = {
  _count: SnapshotWebCountAggregateOutputType | null
  _min: SnapshotWebMinAggregateOutputType | null
  _max: SnapshotWebMaxAggregateOutputType | null
}

export type SnapshotWebMinAggregateOutputType = {
  id: string | null
  sessionId: string | null
  pageUrl: string | null
  data: string | null
  createdOn: Date | null
}

export type SnapshotWebMaxAggregateOutputType = {
  id: string | null
  sessionId: string | null
  pageUrl: string | null
  data: string | null
  createdOn: Date | null
}

export type SnapshotWebCountAggregateOutputType = {
  id: number
  sessionId: number
  pageUrl: number
  data: number
  details: number
  createdOn: number
  _all: number
}


export type SnapshotWebMinAggregateInputType = {
  id?: true
  sessionId?: true
  pageUrl?: true
  data?: true
  createdOn?: true
}

export type SnapshotWebMaxAggregateInputType = {
  id?: true
  sessionId?: true
  pageUrl?: true
  data?: true
  createdOn?: true
}

export type SnapshotWebCountAggregateInputType = {
  id?: true
  sessionId?: true
  pageUrl?: true
  data?: true
  details?: true
  createdOn?: true
  _all?: true
}

export type SnapshotWebAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SnapshotWeb to aggregate.
   */
  where?: Prisma.SnapshotWebWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SnapshotWebs to fetch.
   */
  orderBy?: Prisma.SnapshotWebOrderByWithRelationInput | Prisma.SnapshotWebOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SnapshotWebWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SnapshotWebs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SnapshotWebs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SnapshotWebs
  **/
  _count?: true | SnapshotWebCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SnapshotWebMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SnapshotWebMaxAggregateInputType
}

export type GetSnapshotWebAggregateType<T extends SnapshotWebAggregateArgs> = {
      [P in keyof T & keyof AggregateSnapshotWeb]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSnapshotWeb[P]>
    : Prisma.GetScalarType<T[P], AggregateSnapshotWeb[P]>
}




export type SnapshotWebGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SnapshotWebWhereInput
  orderBy?: Prisma.SnapshotWebOrderByWithAggregationInput | Prisma.SnapshotWebOrderByWithAggregationInput[]
  by: Prisma.SnapshotWebScalarFieldEnum[] | Prisma.SnapshotWebScalarFieldEnum
  having?: Prisma.SnapshotWebScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SnapshotWebCountAggregateInputType | true
  _min?: SnapshotWebMinAggregateInputType
  _max?: SnapshotWebMaxAggregateInputType
}

export type SnapshotWebGroupByOutputType = {
  id: string
  sessionId: string | null
  pageUrl: string
  data: string
  details: runtime.JsonValue | null
  createdOn: Date
  _count: SnapshotWebCountAggregateOutputType | null
  _min: SnapshotWebMinAggregateOutputType | null
  _max: SnapshotWebMaxAggregateOutputType | null
}

export type GetSnapshotWebGroupByPayload<T extends SnapshotWebGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SnapshotWebGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SnapshotWebGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SnapshotWebGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SnapshotWebGroupByOutputType[P]>
      }
    >
  >



export type SnapshotWebWhereInput = {
  AND?: Prisma.SnapshotWebWhereInput | Prisma.SnapshotWebWhereInput[]
  OR?: Prisma.SnapshotWebWhereInput[]
  NOT?: Prisma.SnapshotWebWhereInput | Prisma.SnapshotWebWhereInput[]
  id?: Prisma.StringFilter<"SnapshotWeb"> | string
  sessionId?: Prisma.StringNullableFilter<"SnapshotWeb"> | string | null
  pageUrl?: Prisma.StringFilter<"SnapshotWeb"> | string
  data?: Prisma.StringFilter<"SnapshotWeb"> | string
  details?: Prisma.JsonNullableFilter<"SnapshotWeb">
  createdOn?: Prisma.DateTimeFilter<"SnapshotWeb"> | Date | string
  session?: Prisma.XOR<Prisma.InteractionNullableScalarRelationFilter, Prisma.InteractionWhereInput> | null
}

export type SnapshotWebOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  pageUrl?: Prisma.SortOrder
  data?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  createdOn?: Prisma.SortOrder
  session?: Prisma.InteractionOrderByWithRelationInput
}

export type SnapshotWebWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SnapshotWebWhereInput | Prisma.SnapshotWebWhereInput[]
  OR?: Prisma.SnapshotWebWhereInput[]
  NOT?: Prisma.SnapshotWebWhereInput | Prisma.SnapshotWebWhereInput[]
  sessionId?: Prisma.StringNullableFilter<"SnapshotWeb"> | string | null
  pageUrl?: Prisma.StringFilter<"SnapshotWeb"> | string
  data?: Prisma.StringFilter<"SnapshotWeb"> | string
  details?: Prisma.JsonNullableFilter<"SnapshotWeb">
  createdOn?: Prisma.DateTimeFilter<"SnapshotWeb"> | Date | string
  session?: Prisma.XOR<Prisma.InteractionNullableScalarRelationFilter, Prisma.InteractionWhereInput> | null
}, "id">

export type SnapshotWebOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrderInput | Prisma.SortOrder
  pageUrl?: Prisma.SortOrder
  data?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  createdOn?: Prisma.SortOrder
  _count?: Prisma.SnapshotWebCountOrderByAggregateInput
  _max?: Prisma.SnapshotWebMaxOrderByAggregateInput
  _min?: Prisma.SnapshotWebMinOrderByAggregateInput
}

export type SnapshotWebScalarWhereWithAggregatesInput = {
  AND?: Prisma.SnapshotWebScalarWhereWithAggregatesInput | Prisma.SnapshotWebScalarWhereWithAggregatesInput[]
  OR?: Prisma.SnapshotWebScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SnapshotWebScalarWhereWithAggregatesInput | Prisma.SnapshotWebScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SnapshotWeb"> | string
  sessionId?: Prisma.StringNullableWithAggregatesFilter<"SnapshotWeb"> | string | null
  pageUrl?: Prisma.StringWithAggregatesFilter<"SnapshotWeb"> | string
  data?: Prisma.StringWithAggregatesFilter<"SnapshotWeb"> | string
  details?: Prisma.JsonNullableWithAggregatesFilter<"SnapshotWeb">
  createdOn?: Prisma.DateTimeWithAggregatesFilter<"SnapshotWeb"> | Date | string
}

export type SnapshotWebCreateInput = {
  id?: string
  pageUrl: string
  data: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Date | string
  session?: Prisma.InteractionCreateNestedOneWithoutSnapshotWebsInput
}

export type SnapshotWebUncheckedCreateInput = {
  id?: string
  sessionId?: string | null
  pageUrl: string
  data: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Date | string
}

export type SnapshotWebUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  session?: Prisma.InteractionUpdateOneWithoutSnapshotWebsNestedInput
}

export type SnapshotWebUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SnapshotWebCreateManyInput = {
  id?: string
  sessionId?: string | null
  pageUrl: string
  data: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Date | string
}

export type SnapshotWebUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SnapshotWebUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sessionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SnapshotWebListRelationFilter = {
  every?: Prisma.SnapshotWebWhereInput
  some?: Prisma.SnapshotWebWhereInput
  none?: Prisma.SnapshotWebWhereInput
}

export type SnapshotWebOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SnapshotWebCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  pageUrl?: Prisma.SortOrder
  data?: Prisma.SortOrder
  details?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
}

export type SnapshotWebMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  pageUrl?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
}

export type SnapshotWebMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sessionId?: Prisma.SortOrder
  pageUrl?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdOn?: Prisma.SortOrder
}

export type SnapshotWebCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SnapshotWebCreateWithoutSessionInput, Prisma.SnapshotWebUncheckedCreateWithoutSessionInput> | Prisma.SnapshotWebCreateWithoutSessionInput[] | Prisma.SnapshotWebUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SnapshotWebCreateOrConnectWithoutSessionInput | Prisma.SnapshotWebCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SnapshotWebCreateManySessionInputEnvelope
  connect?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
}

export type SnapshotWebUncheckedCreateNestedManyWithoutSessionInput = {
  create?: Prisma.XOR<Prisma.SnapshotWebCreateWithoutSessionInput, Prisma.SnapshotWebUncheckedCreateWithoutSessionInput> | Prisma.SnapshotWebCreateWithoutSessionInput[] | Prisma.SnapshotWebUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SnapshotWebCreateOrConnectWithoutSessionInput | Prisma.SnapshotWebCreateOrConnectWithoutSessionInput[]
  createMany?: Prisma.SnapshotWebCreateManySessionInputEnvelope
  connect?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
}

export type SnapshotWebUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SnapshotWebCreateWithoutSessionInput, Prisma.SnapshotWebUncheckedCreateWithoutSessionInput> | Prisma.SnapshotWebCreateWithoutSessionInput[] | Prisma.SnapshotWebUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SnapshotWebCreateOrConnectWithoutSessionInput | Prisma.SnapshotWebCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SnapshotWebUpsertWithWhereUniqueWithoutSessionInput | Prisma.SnapshotWebUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SnapshotWebCreateManySessionInputEnvelope
  set?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  disconnect?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  delete?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  connect?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  update?: Prisma.SnapshotWebUpdateWithWhereUniqueWithoutSessionInput | Prisma.SnapshotWebUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SnapshotWebUpdateManyWithWhereWithoutSessionInput | Prisma.SnapshotWebUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SnapshotWebScalarWhereInput | Prisma.SnapshotWebScalarWhereInput[]
}

export type SnapshotWebUncheckedUpdateManyWithoutSessionNestedInput = {
  create?: Prisma.XOR<Prisma.SnapshotWebCreateWithoutSessionInput, Prisma.SnapshotWebUncheckedCreateWithoutSessionInput> | Prisma.SnapshotWebCreateWithoutSessionInput[] | Prisma.SnapshotWebUncheckedCreateWithoutSessionInput[]
  connectOrCreate?: Prisma.SnapshotWebCreateOrConnectWithoutSessionInput | Prisma.SnapshotWebCreateOrConnectWithoutSessionInput[]
  upsert?: Prisma.SnapshotWebUpsertWithWhereUniqueWithoutSessionInput | Prisma.SnapshotWebUpsertWithWhereUniqueWithoutSessionInput[]
  createMany?: Prisma.SnapshotWebCreateManySessionInputEnvelope
  set?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  disconnect?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  delete?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  connect?: Prisma.SnapshotWebWhereUniqueInput | Prisma.SnapshotWebWhereUniqueInput[]
  update?: Prisma.SnapshotWebUpdateWithWhereUniqueWithoutSessionInput | Prisma.SnapshotWebUpdateWithWhereUniqueWithoutSessionInput[]
  updateMany?: Prisma.SnapshotWebUpdateManyWithWhereWithoutSessionInput | Prisma.SnapshotWebUpdateManyWithWhereWithoutSessionInput[]
  deleteMany?: Prisma.SnapshotWebScalarWhereInput | Prisma.SnapshotWebScalarWhereInput[]
}

export type SnapshotWebCreateWithoutSessionInput = {
  id?: string
  pageUrl: string
  data: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Date | string
}

export type SnapshotWebUncheckedCreateWithoutSessionInput = {
  id?: string
  pageUrl: string
  data: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Date | string
}

export type SnapshotWebCreateOrConnectWithoutSessionInput = {
  where: Prisma.SnapshotWebWhereUniqueInput
  create: Prisma.XOR<Prisma.SnapshotWebCreateWithoutSessionInput, Prisma.SnapshotWebUncheckedCreateWithoutSessionInput>
}

export type SnapshotWebCreateManySessionInputEnvelope = {
  data: Prisma.SnapshotWebCreateManySessionInput | Prisma.SnapshotWebCreateManySessionInput[]
  skipDuplicates?: boolean
}

export type SnapshotWebUpsertWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SnapshotWebWhereUniqueInput
  update: Prisma.XOR<Prisma.SnapshotWebUpdateWithoutSessionInput, Prisma.SnapshotWebUncheckedUpdateWithoutSessionInput>
  create: Prisma.XOR<Prisma.SnapshotWebCreateWithoutSessionInput, Prisma.SnapshotWebUncheckedCreateWithoutSessionInput>
}

export type SnapshotWebUpdateWithWhereUniqueWithoutSessionInput = {
  where: Prisma.SnapshotWebWhereUniqueInput
  data: Prisma.XOR<Prisma.SnapshotWebUpdateWithoutSessionInput, Prisma.SnapshotWebUncheckedUpdateWithoutSessionInput>
}

export type SnapshotWebUpdateManyWithWhereWithoutSessionInput = {
  where: Prisma.SnapshotWebScalarWhereInput
  data: Prisma.XOR<Prisma.SnapshotWebUpdateManyMutationInput, Prisma.SnapshotWebUncheckedUpdateManyWithoutSessionInput>
}

export type SnapshotWebScalarWhereInput = {
  AND?: Prisma.SnapshotWebScalarWhereInput | Prisma.SnapshotWebScalarWhereInput[]
  OR?: Prisma.SnapshotWebScalarWhereInput[]
  NOT?: Prisma.SnapshotWebScalarWhereInput | Prisma.SnapshotWebScalarWhereInput[]
  id?: Prisma.StringFilter<"SnapshotWeb"> | string
  sessionId?: Prisma.StringNullableFilter<"SnapshotWeb"> | string | null
  pageUrl?: Prisma.StringFilter<"SnapshotWeb"> | string
  data?: Prisma.StringFilter<"SnapshotWeb"> | string
  details?: Prisma.JsonNullableFilter<"SnapshotWeb">
  createdOn?: Prisma.DateTimeFilter<"SnapshotWeb"> | Date | string
}

export type SnapshotWebCreateManySessionInput = {
  id?: string
  pageUrl: string
  data: string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Date | string
}

export type SnapshotWebUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SnapshotWebUncheckedUpdateWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SnapshotWebUncheckedUpdateManyWithoutSessionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pageUrl?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdOn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SnapshotWebSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  pageUrl?: boolean
  data?: boolean
  details?: boolean
  createdOn?: boolean
  session?: boolean | Prisma.SnapshotWeb$sessionArgs<ExtArgs>
}, ExtArgs["result"]["snapshotWeb"]>

export type SnapshotWebSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  pageUrl?: boolean
  data?: boolean
  details?: boolean
  createdOn?: boolean
  session?: boolean | Prisma.SnapshotWeb$sessionArgs<ExtArgs>
}, ExtArgs["result"]["snapshotWeb"]>

export type SnapshotWebSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sessionId?: boolean
  pageUrl?: boolean
  data?: boolean
  details?: boolean
  createdOn?: boolean
  session?: boolean | Prisma.SnapshotWeb$sessionArgs<ExtArgs>
}, ExtArgs["result"]["snapshotWeb"]>

export type SnapshotWebSelectScalar = {
  id?: boolean
  sessionId?: boolean
  pageUrl?: boolean
  data?: boolean
  details?: boolean
  createdOn?: boolean
}

export type SnapshotWebOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sessionId" | "pageUrl" | "data" | "details" | "createdOn", ExtArgs["result"]["snapshotWeb"]>
export type SnapshotWebInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SnapshotWeb$sessionArgs<ExtArgs>
}
export type SnapshotWebIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SnapshotWeb$sessionArgs<ExtArgs>
}
export type SnapshotWebIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  session?: boolean | Prisma.SnapshotWeb$sessionArgs<ExtArgs>
}

export type $SnapshotWebPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SnapshotWeb"
  objects: {
    session: Prisma.$InteractionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sessionId: string | null
    pageUrl: string
    data: string
    details: runtime.JsonValue | null
    createdOn: Date
  }, ExtArgs["result"]["snapshotWeb"]>
  composites: {}
}

export type SnapshotWebGetPayload<S extends boolean | null | undefined | SnapshotWebDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload, S>

export type SnapshotWebCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SnapshotWebFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SnapshotWebCountAggregateInputType | true
  }

export interface SnapshotWebDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SnapshotWeb'], meta: { name: 'SnapshotWeb' } }
  /**
   * Find zero or one SnapshotWeb that matches the filter.
   * @param {SnapshotWebFindUniqueArgs} args - Arguments to find a SnapshotWeb
   * @example
   * // Get one SnapshotWeb
   * const snapshotWeb = await prisma.snapshotWeb.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SnapshotWebFindUniqueArgs>(args: Prisma.SelectSubset<T, SnapshotWebFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SnapshotWeb that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SnapshotWebFindUniqueOrThrowArgs} args - Arguments to find a SnapshotWeb
   * @example
   * // Get one SnapshotWeb
   * const snapshotWeb = await prisma.snapshotWeb.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SnapshotWebFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SnapshotWebFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SnapshotWeb that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnapshotWebFindFirstArgs} args - Arguments to find a SnapshotWeb
   * @example
   * // Get one SnapshotWeb
   * const snapshotWeb = await prisma.snapshotWeb.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SnapshotWebFindFirstArgs>(args?: Prisma.SelectSubset<T, SnapshotWebFindFirstArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SnapshotWeb that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnapshotWebFindFirstOrThrowArgs} args - Arguments to find a SnapshotWeb
   * @example
   * // Get one SnapshotWeb
   * const snapshotWeb = await prisma.snapshotWeb.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SnapshotWebFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SnapshotWebFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SnapshotWebs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnapshotWebFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SnapshotWebs
   * const snapshotWebs = await prisma.snapshotWeb.findMany()
   * 
   * // Get first 10 SnapshotWebs
   * const snapshotWebs = await prisma.snapshotWeb.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const snapshotWebWithIdOnly = await prisma.snapshotWeb.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SnapshotWebFindManyArgs>(args?: Prisma.SelectSubset<T, SnapshotWebFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SnapshotWeb.
   * @param {SnapshotWebCreateArgs} args - Arguments to create a SnapshotWeb.
   * @example
   * // Create one SnapshotWeb
   * const SnapshotWeb = await prisma.snapshotWeb.create({
   *   data: {
   *     // ... data to create a SnapshotWeb
   *   }
   * })
   * 
   */
  create<T extends SnapshotWebCreateArgs>(args: Prisma.SelectSubset<T, SnapshotWebCreateArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SnapshotWebs.
   * @param {SnapshotWebCreateManyArgs} args - Arguments to create many SnapshotWebs.
   * @example
   * // Create many SnapshotWebs
   * const snapshotWeb = await prisma.snapshotWeb.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SnapshotWebCreateManyArgs>(args?: Prisma.SelectSubset<T, SnapshotWebCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SnapshotWebs and returns the data saved in the database.
   * @param {SnapshotWebCreateManyAndReturnArgs} args - Arguments to create many SnapshotWebs.
   * @example
   * // Create many SnapshotWebs
   * const snapshotWeb = await prisma.snapshotWeb.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SnapshotWebs and only return the `id`
   * const snapshotWebWithIdOnly = await prisma.snapshotWeb.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SnapshotWebCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SnapshotWebCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SnapshotWeb.
   * @param {SnapshotWebDeleteArgs} args - Arguments to delete one SnapshotWeb.
   * @example
   * // Delete one SnapshotWeb
   * const SnapshotWeb = await prisma.snapshotWeb.delete({
   *   where: {
   *     // ... filter to delete one SnapshotWeb
   *   }
   * })
   * 
   */
  delete<T extends SnapshotWebDeleteArgs>(args: Prisma.SelectSubset<T, SnapshotWebDeleteArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SnapshotWeb.
   * @param {SnapshotWebUpdateArgs} args - Arguments to update one SnapshotWeb.
   * @example
   * // Update one SnapshotWeb
   * const snapshotWeb = await prisma.snapshotWeb.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SnapshotWebUpdateArgs>(args: Prisma.SelectSubset<T, SnapshotWebUpdateArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SnapshotWebs.
   * @param {SnapshotWebDeleteManyArgs} args - Arguments to filter SnapshotWebs to delete.
   * @example
   * // Delete a few SnapshotWebs
   * const { count } = await prisma.snapshotWeb.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SnapshotWebDeleteManyArgs>(args?: Prisma.SelectSubset<T, SnapshotWebDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SnapshotWebs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnapshotWebUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SnapshotWebs
   * const snapshotWeb = await prisma.snapshotWeb.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SnapshotWebUpdateManyArgs>(args: Prisma.SelectSubset<T, SnapshotWebUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SnapshotWebs and returns the data updated in the database.
   * @param {SnapshotWebUpdateManyAndReturnArgs} args - Arguments to update many SnapshotWebs.
   * @example
   * // Update many SnapshotWebs
   * const snapshotWeb = await prisma.snapshotWeb.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SnapshotWebs and only return the `id`
   * const snapshotWebWithIdOnly = await prisma.snapshotWeb.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SnapshotWebUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SnapshotWebUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SnapshotWeb.
   * @param {SnapshotWebUpsertArgs} args - Arguments to update or create a SnapshotWeb.
   * @example
   * // Update or create a SnapshotWeb
   * const snapshotWeb = await prisma.snapshotWeb.upsert({
   *   create: {
   *     // ... data to create a SnapshotWeb
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SnapshotWeb we want to update
   *   }
   * })
   */
  upsert<T extends SnapshotWebUpsertArgs>(args: Prisma.SelectSubset<T, SnapshotWebUpsertArgs<ExtArgs>>): Prisma.Prisma__SnapshotWebClient<runtime.Types.Result.GetResult<Prisma.$SnapshotWebPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SnapshotWebs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnapshotWebCountArgs} args - Arguments to filter SnapshotWebs to count.
   * @example
   * // Count the number of SnapshotWebs
   * const count = await prisma.snapshotWeb.count({
   *   where: {
   *     // ... the filter for the SnapshotWebs we want to count
   *   }
   * })
  **/
  count<T extends SnapshotWebCountArgs>(
    args?: Prisma.Subset<T, SnapshotWebCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SnapshotWebCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SnapshotWeb.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnapshotWebAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SnapshotWebAggregateArgs>(args: Prisma.Subset<T, SnapshotWebAggregateArgs>): Prisma.PrismaPromise<GetSnapshotWebAggregateType<T>>

  /**
   * Group by SnapshotWeb.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SnapshotWebGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SnapshotWebGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SnapshotWebGroupByArgs['orderBy'] }
      : { orderBy?: SnapshotWebGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SnapshotWebGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSnapshotWebGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SnapshotWeb model
 */
readonly fields: SnapshotWebFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SnapshotWeb.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SnapshotWebClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  session<T extends Prisma.SnapshotWeb$sessionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SnapshotWeb$sessionArgs<ExtArgs>>): Prisma.Prisma__InteractionClient<runtime.Types.Result.GetResult<Prisma.$InteractionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SnapshotWeb model
 */
export interface SnapshotWebFieldRefs {
  readonly id: Prisma.FieldRef<"SnapshotWeb", 'String'>
  readonly sessionId: Prisma.FieldRef<"SnapshotWeb", 'String'>
  readonly pageUrl: Prisma.FieldRef<"SnapshotWeb", 'String'>
  readonly data: Prisma.FieldRef<"SnapshotWeb", 'String'>
  readonly details: Prisma.FieldRef<"SnapshotWeb", 'Json'>
  readonly createdOn: Prisma.FieldRef<"SnapshotWeb", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SnapshotWeb findUnique
 */
export type SnapshotWebFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * Filter, which SnapshotWeb to fetch.
   */
  where: Prisma.SnapshotWebWhereUniqueInput
}

/**
 * SnapshotWeb findUniqueOrThrow
 */
export type SnapshotWebFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * Filter, which SnapshotWeb to fetch.
   */
  where: Prisma.SnapshotWebWhereUniqueInput
}

/**
 * SnapshotWeb findFirst
 */
export type SnapshotWebFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * Filter, which SnapshotWeb to fetch.
   */
  where?: Prisma.SnapshotWebWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SnapshotWebs to fetch.
   */
  orderBy?: Prisma.SnapshotWebOrderByWithRelationInput | Prisma.SnapshotWebOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SnapshotWebs.
   */
  cursor?: Prisma.SnapshotWebWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SnapshotWebs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SnapshotWebs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SnapshotWebs.
   */
  distinct?: Prisma.SnapshotWebScalarFieldEnum | Prisma.SnapshotWebScalarFieldEnum[]
}

/**
 * SnapshotWeb findFirstOrThrow
 */
export type SnapshotWebFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * Filter, which SnapshotWeb to fetch.
   */
  where?: Prisma.SnapshotWebWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SnapshotWebs to fetch.
   */
  orderBy?: Prisma.SnapshotWebOrderByWithRelationInput | Prisma.SnapshotWebOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SnapshotWebs.
   */
  cursor?: Prisma.SnapshotWebWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SnapshotWebs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SnapshotWebs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SnapshotWebs.
   */
  distinct?: Prisma.SnapshotWebScalarFieldEnum | Prisma.SnapshotWebScalarFieldEnum[]
}

/**
 * SnapshotWeb findMany
 */
export type SnapshotWebFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * Filter, which SnapshotWebs to fetch.
   */
  where?: Prisma.SnapshotWebWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SnapshotWebs to fetch.
   */
  orderBy?: Prisma.SnapshotWebOrderByWithRelationInput | Prisma.SnapshotWebOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SnapshotWebs.
   */
  cursor?: Prisma.SnapshotWebWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SnapshotWebs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SnapshotWebs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SnapshotWebs.
   */
  distinct?: Prisma.SnapshotWebScalarFieldEnum | Prisma.SnapshotWebScalarFieldEnum[]
}

/**
 * SnapshotWeb create
 */
export type SnapshotWebCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * The data needed to create a SnapshotWeb.
   */
  data: Prisma.XOR<Prisma.SnapshotWebCreateInput, Prisma.SnapshotWebUncheckedCreateInput>
}

/**
 * SnapshotWeb createMany
 */
export type SnapshotWebCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SnapshotWebs.
   */
  data: Prisma.SnapshotWebCreateManyInput | Prisma.SnapshotWebCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SnapshotWeb createManyAndReturn
 */
export type SnapshotWebCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * The data used to create many SnapshotWebs.
   */
  data: Prisma.SnapshotWebCreateManyInput | Prisma.SnapshotWebCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SnapshotWeb update
 */
export type SnapshotWebUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * The data needed to update a SnapshotWeb.
   */
  data: Prisma.XOR<Prisma.SnapshotWebUpdateInput, Prisma.SnapshotWebUncheckedUpdateInput>
  /**
   * Choose, which SnapshotWeb to update.
   */
  where: Prisma.SnapshotWebWhereUniqueInput
}

/**
 * SnapshotWeb updateMany
 */
export type SnapshotWebUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SnapshotWebs.
   */
  data: Prisma.XOR<Prisma.SnapshotWebUpdateManyMutationInput, Prisma.SnapshotWebUncheckedUpdateManyInput>
  /**
   * Filter which SnapshotWebs to update
   */
  where?: Prisma.SnapshotWebWhereInput
  /**
   * Limit how many SnapshotWebs to update.
   */
  limit?: number
}

/**
 * SnapshotWeb updateManyAndReturn
 */
export type SnapshotWebUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * The data used to update SnapshotWebs.
   */
  data: Prisma.XOR<Prisma.SnapshotWebUpdateManyMutationInput, Prisma.SnapshotWebUncheckedUpdateManyInput>
  /**
   * Filter which SnapshotWebs to update
   */
  where?: Prisma.SnapshotWebWhereInput
  /**
   * Limit how many SnapshotWebs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SnapshotWeb upsert
 */
export type SnapshotWebUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * The filter to search for the SnapshotWeb to update in case it exists.
   */
  where: Prisma.SnapshotWebWhereUniqueInput
  /**
   * In case the SnapshotWeb found by the `where` argument doesn't exist, create a new SnapshotWeb with this data.
   */
  create: Prisma.XOR<Prisma.SnapshotWebCreateInput, Prisma.SnapshotWebUncheckedCreateInput>
  /**
   * In case the SnapshotWeb was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SnapshotWebUpdateInput, Prisma.SnapshotWebUncheckedUpdateInput>
}

/**
 * SnapshotWeb delete
 */
export type SnapshotWebDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
  /**
   * Filter which SnapshotWeb to delete.
   */
  where: Prisma.SnapshotWebWhereUniqueInput
}

/**
 * SnapshotWeb deleteMany
 */
export type SnapshotWebDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SnapshotWebs to delete
   */
  where?: Prisma.SnapshotWebWhereInput
  /**
   * Limit how many SnapshotWebs to delete.
   */
  limit?: number
}

/**
 * SnapshotWeb.session
 */
export type SnapshotWeb$sessionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Interaction
   */
  select?: Prisma.InteractionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Interaction
   */
  omit?: Prisma.InteractionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InteractionInclude<ExtArgs> | null
  where?: Prisma.InteractionWhereInput
}

/**
 * SnapshotWeb without action
 */
export type SnapshotWebDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SnapshotWeb
   */
  select?: Prisma.SnapshotWebSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SnapshotWeb
   */
  omit?: Prisma.SnapshotWebOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SnapshotWebInclude<ExtArgs> | null
}
