
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const InteractionEventType = {
  mousemove: 'mousemove',
  click: 'click',
  scroll: 'scroll',
  touch: 'touch',
  input: 'input',
  keydown: 'keydown',
  pageview: 'pageview',
  heartbeat: 'heartbeat'
} as const

export type InteractionEventType = (typeof InteractionEventType)[keyof typeof InteractionEventType]


export const ApplicationStatus = {
  setup: 'setup',
  active: 'active'
} as const

export type ApplicationStatus = (typeof ApplicationStatus)[keyof typeof ApplicationStatus]


export const IpMapType = {
  ip4: 'ip4',
  ip6: 'ip6',
  dev: 'dev'
} as const

export type IpMapType = (typeof IpMapType)[keyof typeof IpMapType]
