// Regenerate both distributed sources from the expanded implementations.
const fs = require('node:fs');
const ts = require('typescript');
const { minify } = require('next/dist/compiled/terser');
const directory = 'app/bridge/sdk.v1/tracker';

async function generate() {
  const sdk = require('./load-tracker.cjs').loadTrackerModule(`${directory}/expanded.client.ts`);
  const compactClient = await minify(sdk.clientSource);
  // Keep identifiers stable across independently minified runtime and modules.
  const clientTemplate = await minify(sdk.buildClientSource('__template__'), { compress: false, mangle: false });
  const modules = {};
  for (const [name, entry] of Object.entries(sdk.eventModules)) {
    modules[name] = { aliases: entry.aliases, source: (await minify(entry.source, { compress: false, mangle: false })).code };
  }
  const outputs = { 'minified.client.ts': `// Generated by npm run tracker:build. Edit expanded.client.ts instead.
export const clientSource = ${JSON.stringify(compactClient.code)};
const template = ${JSON.stringify(clientTemplate.code)};
const modules: Record<string, { aliases: string[]; source: string }> = ${JSON.stringify(modules)};
export function buildClientSource(requested: string): string {
  const selected = requested.split(',').map(value => value.trim().toLowerCase());
  return template.replace(/"NEUP_MODULE_([^"]+)";/g, (_marker, name: string) => {
    const entry = modules[name];
    return entry && !selected.includes('none') && (selected.includes('all') || entry.aliases.some(alias => selected.includes(alias))) ? entry.source : '';
  });
}
` };

  const server = ts.createSourceFile('expanded.server.ts', fs.readFileSync(`${directory}/expanded.server.ts`, 'utf8'), ts.ScriptTarget.Latest, true);
  const builder = server.statements.find(node => ts.isFunctionDeclaration(node) && node.name.text === 'buildAnalyticsCode');
  const template = builder.body.statements.find(ts.isReturnStatement).expression;
  const expressions = template.templateSpans.map(span => span.expression.getText(server));
  // Substitute valid identifiers before compiling the generated TypeScript.
  // Markers also work inside quoted project IDs and URLs.
  let source = template.head.text;
  template.templateSpans.forEach((span, index) => { source += `NEUP_TEMPLATE_${index}_VALUE` + span.literal.text; });
  const javascript = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2017, module: ts.ModuleKind.ESNext } }).outputText;
  const compactServer = await minify(javascript, { module: true });
  const parts = compactServer.code.split(/(NEUP_TEMPLATE_\d+_VALUE)/);
  const expression = parts.map(part => {
    const match = /^NEUP_TEMPLATE_(\d+)_VALUE$/.exec(part);
    return match ? `(${expressions[Number(match[1])]})` : JSON.stringify(part);
  }).join(' + ');
  outputs['minified.server.ts'] = '// Generated by npm run tracker:build. Edit expanded.server.ts instead.\n'
    + "import { trackingFields, type TrackingOptions } from '@/components/tracking-options';\n"
    + `export function buildAnalyticsCode(projectId: string, tracking: TrackingOptions): string { return ${expression}; }\n`;
  for (const [name, content] of Object.entries(outputs)) {
    const path = `${directory}/${name}`;
    if (process.argv.includes('--check')) {
      if (!fs.existsSync(path) || fs.readFileSync(path, 'utf8') !== content) throw new Error(`${name} is stale; run npm run tracker:build`);
    } else fs.writeFileSync(path, content);
  }
}
generate().catch(error => { console.error(error); process.exitCode = 1; });
